# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goplaces < Formula
  desc "Modern Go client + CLI for the Google Places API (New)."
  homepage "https://github.com/steipete/goplaces"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.1/goplaces_0.4.1_darwin_amd64.tar.gz"
      sha256 "77e9936b74720fe5ff4706ceb66ad56f58988ca3ff92231ed48c4a7f7ce5a9ea"

      define_method(:install) do
        bin.install "goplaces"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.1/goplaces_0.4.1_darwin_arm64.tar.gz"
      sha256 "a5369eba0857ac163dcb52ab94c15202b19110d64feae5e383b19e80348fd89a"

      define_method(:install) do
        bin.install "goplaces"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.1/goplaces_0.4.1_linux_amd64.tar.gz"
      sha256 "69b54fe91183643d4622e26a84501e78e4fc71a5e801ed4a50181bd2d3a4572c"
      define_method(:install) do
        bin.install "goplaces"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.1/goplaces_0.4.1_linux_arm64.tar.gz"
      sha256 "7407200e1a48ef241acc2c9e85074e41f4858645c1a95a7f89c698067929d747"
      define_method(:install) do
        bin.install "goplaces"
      end
    end
  end

  test do
    system "#{bin}/goplaces", "--version"
  end
end
