# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goplaces < Formula
  desc "Modern Go client + CLI for the Google Places API (New)."
  homepage "https://github.com/steipete/goplaces"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.1/goplaces_0.4.1_darwin_amd64.tar.gz"
      sha256 "5aa62ed8ec6d8935d4fa52b6ede05e5a9b2cf9e80122d623aa157bcc6e715754"

      define_method(:install) do
        bin.install "goplaces"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.1/goplaces_0.4.1_darwin_arm64.tar.gz"
      sha256 "49229a52e226b9543b81e699fab3ee89e9ac52d76e7d07a004b9788673d45790"

      define_method(:install) do
        bin.install "goplaces"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.1/goplaces_0.4.1_linux_amd64.tar.gz"
      sha256 "7479b393881db52d88dcc62bc9113ecf0252d272d62be717dbc9644c27c340ac"
      define_method(:install) do
        bin.install "goplaces"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.1/goplaces_0.4.1_linux_arm64.tar.gz"
      sha256 "401aa0993a2cc660f1247ae07e731a1f4696c2780c369de57a78a882e9339b1e"
      define_method(:install) do
        bin.install "goplaces"
      end
    end
  end

  test do
    system "#{bin}/goplaces", "--version"
  end
end
