# typed: false
# frozen_string_literal: true

# Generated by the protected Crabbox release tooling. DO NOT EDIT.
class Crabbox < Formula
  desc "Remote software testing and execution"
  homepage "https://github.com/openclaw/crabbox"
  version "0.41.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openclaw/crabbox/releases/download/v0.41.5/crabbox_0.41.5_darwin_amd64.tar.gz"
      sha256 "f5346be7a11b7d25f3f08033e0c10f785830ce6de1e323822a00e10ce1e41206"

      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openclaw/crabbox/releases/download/v0.41.5/crabbox_0.41.5_darwin_arm64.tar.gz"
      sha256 "688298c47706b5ca828e2a49741ce9571ad1ebd52a891217ae40d9c8d999e86d"

      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/crabbox/releases/download/v0.41.5/crabbox_0.41.5_linux_amd64.tar.gz"
      sha256 "cebbbff1806ca1270350df1ed374c1a00897a2f34e52329f03abf6a9e3fbef50"
      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/crabbox/releases/download/v0.41.5/crabbox_0.41.5_linux_arm64.tar.gz"
      sha256 "73a60327b3b589c73687df856ac20e86fde7bffc3ba472c2b06162682c8ea3ac"
      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
  end

  test do
    system bin/"crabbox", "--version"
  end
end
