# typed: false
# frozen_string_literal: true

# Generated by the protected Crabbox release tooling. DO NOT EDIT.
class Crabbox < Formula
  desc "Remote software testing and execution"
  homepage "https://github.com/openclaw/crabbox"
  version "0.39.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openclaw/crabbox/releases/download/v0.39.0/crabbox_0.39.0_darwin_amd64.tar.gz"
      sha256 "e02b04be8fd2c23287871c73afe18880af33be58bba4acc770f2f6d05825d119"

      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openclaw/crabbox/releases/download/v0.39.0/crabbox_0.39.0_darwin_arm64.tar.gz"
      sha256 "5bfd092707e94a0e52846b382d6296110565c66bd96d49bacd2c55ae53684084"

      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/crabbox/releases/download/v0.39.0/crabbox_0.39.0_linux_amd64.tar.gz"
      sha256 "ebc7de1d6586423ff83936911028bc3f9cd718f188fa0ed4e4e0f1fbcfcfda43"
      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/crabbox/releases/download/v0.39.0/crabbox_0.39.0_linux_arm64.tar.gz"
      sha256 "b7b08f25f217a97d6b6e5ba337917ba11758e87a73681d3c0f1d541aea0f573c"
      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
  end

  test do
    system bin/"crabbox", "--version"
  end
end
