# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goplaces < Formula
  desc "Modern Go client + CLI for the Google Places API (New)."
  homepage "https://github.com/steipete/goplaces"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.2/goplaces_0.4.2_darwin_amd64.tar.gz"
      sha256 "71d8987d4ac3b31eec66dc8e338a10a78d6e6e8528b7f1e2780c77a66500c942"

      define_method(:install) do
        bin.install "goplaces"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.2/goplaces_0.4.2_darwin_arm64.tar.gz"
      sha256 "69e7a5b7452f6f095694d3f8ede86df6d2287cbbd3371f31c806826d828b5f26"

      define_method(:install) do
        bin.install "goplaces"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.2/goplaces_0.4.2_linux_amd64.tar.gz"
      sha256 "26689c165dac3d64741193487807f2ac48263bd68e431a69a86384cf212a8ea9"
      define_method(:install) do
        bin.install "goplaces"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/goplaces/releases/download/v0.4.2/goplaces_0.4.2_linux_arm64.tar.gz"
      sha256 "96edb8918cb8b2df4d34c49349fc6aeae91ee94fd4d5e008441952aac1637d56"
      define_method(:install) do
        bin.install "goplaces"
      end
    end
  end

  test do
    system "#{bin}/goplaces", "--version"
  end
end
